// Sensible defaults for the calculator. Tuned to a typical mid-market
// Canadian condo / townhouse circa 2024-2025.
export const DEFAULT_INPUTS = {
  propertyPrice: 1_050_000,
  downPayment: 157_500,
  amortization: 25,
  mortgageRate: 4.5,
  propertyGrowth: 3,
  fixedExpenses: 1_558,
  expenseInflation: 2,
  initialRent: 3_500,
  rentIncrease: 2,
  marketReturn: 7,
  years: 10,
  applySaleCost: true,
  saleCostPct: 5,

  // Cash-to-close (province-aware, computed in auto mode).
  closingCostsMode: "auto", // "auto" | "manual"
  province: "ON",
  firstTimeBuyer: false,
  newConstruction: false,
  includeTorontoLtt: false,
  otherClosingCosts: 2_500,
  closingCostsManual: 15_750, // used only when closingCostsMode === "manual"
};

// `kind: "slider"` fields render a track with a precise number input next to
// the value. `kind: "number"` fields use a plain input. Sliders are reserved
// for bounded percentage-like inputs where dragging is useful for exploration.
export const FIELD_META = {
  propertyPrice: {
    kind: "number",
    label: "Property price",
    suffix: "$",
    step: 5000,
    min: 0,
    help: "Listed or expected purchase price.",
    group: "property",
  },
  downPayment: {
    kind: "downPaymentPct",
    label: "Down payment",
    suffix: "%",
    step: 0.5,
    min: 0,
    max: 100,
    help: "Percent of the property price you pay in cash at closing. The remainder is financed. Canadian minimum: 5% on the first $500k, 10% on $500k–$1.5M, 20% above $1.5M. Drag the slider or type a precise percentage.",
    group: "property",
  },
  otherClosingCosts: {
    kind: "number",
    label: "Legal / title / inspection",
    suffix: "$",
    step: 100,
    min: 0,
    help: "Non-tax closing costs: lawyer ($1.5–2.5k), title insurance ($300–500), home inspection or appraisal ($500–1k). Land transfer tax and GST/HST are auto-computed below.",
    group: "property",
  },
  closingCostsManual: {
    kind: "number",
    label: "Closing costs (manual override)",
    suffix: "$",
    step: 250,
    min: 0,
    help: "Used when the closing-costs mode is set to Manual. Replaces the province-aware breakdown with a single lump-sum number.",
    group: "property",
  },
  amortization: {
    kind: "amortizationChoice",
    label: "Amortization",
    help: "Canadian insured mortgages (down < 20%) are usually 25 years. 30-year amortization is available for many first-time buyers and new builds; CMHC adds a 0.20% surcharge on the insurance premium when amortization exceeds 25 years.",
    group: "mortgage",
  },
  mortgageRate: {
    kind: "slider",
    label: "Mortgage rate",
    suffix: "%",
    step: 0.05,
    min: 0,
    max: 12,
    help: "Nominal annual rate. Canadian mortgages compound semi-annually, so the effective monthly rate is (1 + r/2)^(1/6) − 1, slightly less than r/12.",
    group: "mortgage",
  },
  fixedExpenses: {
    kind: "number",
    label: "Monthly ownership costs",
    suffix: "$",
    step: 50,
    min: 0,
    help: "Property tax, insurance, condo / strata fees, and maintenance. Anything you only pay as an owner.",
    group: "mortgage",
  },
  expenseInflation: {
    kind: "slider",
    label: "Expense inflation",
    suffix: "%",
    step: 0.1,
    min: 0,
    max: 8,
    help: "Annual growth in ownership costs. Property tax and condo fees usually track inflation or rise faster.",
    group: "mortgage",
  },
  propertyGrowth: {
    kind: "slider",
    label: "Property appreciation",
    suffix: "%",
    step: 0.1,
    min: -5,
    max: 10,
    help: "Annual change in market value. Long-run Canadian real-house-price growth has been near inflation; in some metros it has been higher.",
    group: "mortgage",
  },
  initialRent: {
    kind: "number",
    label: "Monthly rent",
    suffix: "$",
    step: 50,
    min: 0,
    help: "Rent for an equivalent property today.",
    group: "rent",
  },
  rentIncrease: {
    kind: "slider",
    label: "Annual rent increase",
    suffix: "%",
    step: 0.1,
    min: 0,
    max: 8,
    help: "Compounded yearly. Provincial guidelines (e.g. Ontario, BC) usually cap this between 2% and 4%.",
    group: "rent",
  },
  marketReturn: {
    kind: "slider",
    label: "Market return",
    suffix: "%",
    step: 0.1,
    min: -5,
    max: 15,
    help: "Expected long-run nominal return on the renter's portfolio. A globally-diversified equity portfolio has historically returned 6–9% nominal.",
    group: "rent",
  },
  years: {
    kind: "number",
    label: "Time horizon",
    suffix: "yrs",
    step: 1,
    min: 1,
    max: 40,
    help: "Length of the comparison. Longer horizons usually favour the path with the higher compound growth rate.",
    group: "horizon",
  },
  saleCostPct: {
    kind: "slider",
    label: "Sale cost",
    suffix: "%",
    step: 0.1,
    min: 0,
    max: 10,
    help: "Realtor commission, legal fees, and discharge cost as a percentage of sale price. In Canada this is typically 4–6%.",
    group: "horizon",
  },
};
